### PR TITLE
Added function for summing intensity values.

### PR DESCRIPTION
**Pull request by FloWuenne**
Simple PR that adds a function to perform summing of intensities per mask. 

User can activate summing by supplying ` --intensity_props mask_sum` to the `CommandSingleCellExtraction.py`.

### CODE REVIEW

**Comment by ArtemSokolov** [comment]
Hi @FloWuenne,

Can you please rename the function to `intensity_sum()` to be consistent with other similar regionprops functions like `intensity_mean()`, `intensity_max()`, etc.?

-Artem

**Comment by FloWuenne** [comment]
@ArtemSokolov I changed the function name as you suggested!

**Comment by jmuhlich** [comment]
Can you also document this in the README under the `--intensity_props` option? That bit needs to be reworked now that we have a few of these extra properties but you don't have to do that in this PR if you don't want to -- you can just add a sentence to explain `intensity_sum` to the existing paragraph. I've filed #44 to remind us about reformatting it later.

**Comment by FloWuenne** [comment]
My last commit adds documentation for intensity_sum() and should solve #44!

**Pull request merged**
